apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-goodbye-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: echo-hello
      taskRef:
        name: task-echo-hello-world
    - name: git-clone
      runAfter: [echo-hello]
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/peachycloudsecurity/pipeline-craft
        - name: revision
          value: master
    - name: build-and-push
      runAfter: [git-clone]
      taskRef:
        name: build-and-push
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: docker.io/gurubaba/tekton-demo:latest
