apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: taskrun-build-and-push
spec:
  taskRef:
    name: build-and-push
  params:
    - name: IMAGE
      value: docker.io/gurubaba/tekton-demo:latest
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-pvc
