apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: git-clone-taskrun
spec:
  taskRef:
    name: git-clone
  params:
    - name: url
      value: https://github.com/peachycloudsecurity/pipeline-craft
    - name: revision
      value: master
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: tekton-pvc
