apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: IMAGE
      type: string
  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=$(workspaces.shared-workspace.path)/Dockerfile
        - --context=$(workspaces.shared-workspace.path)/
        - --destination=$(params.IMAGE)
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
        items:
          - key: .dockerconfigjson
            path: config.json
