apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: trivy-scan
spec:
  params:
    - name: IMAGE_URL
      type: string
  steps:
    - name: trivy-scan
      image: aquasec/trivy:latest
      script: |
        trivy image --severity CRITICAL --no-progress $(params.IMAGE_URL)
