apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-tests
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:18-alpine
      script: |
        cd $(workspaces.source.path)
        npm install
        npm test
        echo "Tests passed!"
