apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-app
spec:
  workspaces:
    - name: source
  params:
    - name: image-name
      type: string
  steps:
    - name: build
      image: node:18-alpine
      script: |
        cd $(workspaces.source.path)
        npm install
        npm run build
        echo "Build completed!"
