apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-app
spec:
  params:
    - name: namespace
      type: string
      default: "default"
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      script: |
        kubectl create namespace $(params.namespace) --dry-run=client -o yaml | kubectl apply -f -
        echo "Deployed to namespace: $(params.namespace)"
